// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_COMMERCE.Models
{
    public partial class Carrello
    {
        public int IdCarrello { get; set; }
        public double? Total { get; set; }
    }
}