// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace E_COMMERCE.Models
{
    public partial class ECOMMERCEContext : DbContext
    {
        public ECOMMERCEContext()
        {
        }

        public ECOMMERCEContext(DbContextOptions<ECOMMERCEContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Carrello> Carrellos { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Negozio> Negozios { get; set; }
        public virtual DbSet<Prodotto> Prodottos { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Carrello>(entity =>
            {
                entity.HasKey(e => e.IdCarrello)
                    .HasName("PK__CARRELLO__7C117356BEC78979");

                entity.ToTable("CARRELLO");

                entity.Property(e => e.IdCarrello)
                    .ValueGeneratedNever()
                    .HasColumnName("id_carrello");

                entity.Property(e => e.Total).HasColumnName("total");
            });

            modelBuilder.Entity<Cliente>(entity =>
            {
                entity.HasKey(e => e.IdCliente)
                    .HasName("PK__CLIENTE__677F38F5791000BC");

                entity.ToTable("CLIENTE");

                entity.Property(e => e.IdCliente)
                    .ValueGeneratedNever()
                    .HasColumnName("id_cliente");

                entity.Property(e => e.Cognome)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("cognome");

                entity.Property(e => e.Nome)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("nome");
            });

            modelBuilder.Entity<Negozio>(entity =>
            {
                entity.HasKey(e => e.IdNegozio)
                    .HasName("PK__NEGOZIO__015BC2DE57CF7560");

                entity.ToTable("NEGOZIO");

                entity.Property(e => e.IdNegozio)
                    .ValueGeneratedNever()
                    .HasColumnName("id_negozio");

                entity.Property(e => e.Prodotto)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("prodotto");
            });

            modelBuilder.Entity<Prodotto>(entity =>
            {
                entity.HasKey(e => e.IdProdotto)
                    .HasName("PK__PRODOTTO__EC110BE9D546A32D");

                entity.ToTable("PRODOTTO");

                entity.Property(e => e.IdProdotto)
                    .ValueGeneratedNever()
                    .HasColumnName("id_prodotto");

                entity.Property(e => e.Nome)
                    .HasMaxLength(15)
                    .IsUnicode(false)
                    .HasColumnName("nome");

                entity.Property(e => e.Prezzo).HasColumnName("prezzo");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}