// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_COMMERCE.Models
{
    public partial class Negozio
    {
        public int IdNegozio { get; set; }
        public string Prodotto { get; set; }
    }
}