// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_COMMERCE.Models
{
    public partial class Prodotto
    {
        public int IdProdotto { get; set; }
        public string Nome { get; set; }
        public double? Prezzo { get; set; }
    }
}